A8 s 2144 Remove hardcoded start commands
anynines/a8s-deployment pull request #319
Opened 2024-07-05 08:01 UTC by m-hofmann-a9s

# Short Description

* remove hard-coded start commands from deployment manifests to allow using either buildpack or buildx-created images by relying on default entrypoint
* fix links in README.me (housekeeping)

# Details

Deployment has been tested by applying the manifests on kind. Pods start successfully.

# Note

WARNING: Only users listed in the CODEOWNERS file can approve PRs!

# Checks

- [x] Documentation has been adjusted
- [x] Architectural decisions have been documented -> not applicable, implementation detail
- [x] Changelog has been updated
- [ ] PR is approved by a code owner
- [ ] Manifests are updated
- [ ] Commit message adheres to our [guideline](https://anynines.atlassian.net/wiki/spaces/DS/pages/2423193626/Version+Control+Workflow)

2024-07-05 08:04 UTC, lhaendler requested changes, later dismissed
The manifests are generated from the individual components' repos config folder, and propagated to a8s-deployment. Please change them in the components to avoid the change being overwritten by automation

2024-07-09 13:10 UTC, mkfdoherty approved these changes, later dismissed

2024-07-17 11:03 UTC, m-hofmann-a9s commented
@lhaendler upstream repos have been upgrade:

- https://github.com/anynines/a8s-service-binding-controller/pull/71
- https://github.com/anynines/postgresql-operator/pull/207
- https://github.com/anynines/a8s-backup-manager/pull/90

2024-08-06 10:41 UTC, mkfdoherty approved these changes

2024-08-06 10:41 UTC, merged